Test: NotificationFragmentTest
CMPUT301F20T09/PocketBook pull request #234
Opened 2020-11-29 13:07 UTC by MahmoudAJ2000

still incomplete but it has one passing test

2020-11-29 15:52 UTC, aakindel approved these changes

2020-11-29 16:04 UTC, aakindel requested changes
Could you make sure that the test data is deleted from Firebase?

2020-11-29 17:51 UTC, MahmoodFalmaz approved these changes

2020-11-30 15:35 UTC, aakindel approved these changes

2020-11-30 15:35 UTC, merged