refactor: worked on ViewMyBookActivity Firebase integration
CMPUT301F20T09/PocketBook pull request #45
Opened 2020-10-26 06:19 UTC by aakindel

The basic setup for getting a book's information from Firebase and into the app is mostly functional.

2020-10-26 08:01 UTC, thefreezer commented on app/src/main/java/com/example/pocketbook/activity/ViewMyBookActivity.java
> +        mAuth.signInWithEmailAndPassword(email, password)
Will this call be removed once the Login page is setup?

2020-10-26 23:08 UTC, MahmoodFalmaz approved these changes
Approved

2020-10-27 04:01 UTC, Head8che approved these changes
Approved

2020-10-27 04:01 UTC, Head8che requested changes
Pending

2020-10-27 05:53 UTC, Head8che approved these changes
Approved

2020-10-27 05:53 UTC, merged